services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8082:8081"
    volumes:
      - /mnt/cloud_hdd/data/downloads/metube:/downloads
      - /etc/nginx/certs/malzalab-metube.home.pem:/ssl/crt.pem
      - /etc/nginx/certs/malzalab-metube.home-key.pem:/ssl/key.pem
    environment:
      - HTTPS=true
      - CERTFILE=/ssl/crt.pem
      - KEYFILE=/ssl/key.pem
