services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: always
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /mnt/cloud_hdd:/mnt/cloud_hdd:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8088:8080
    env_file: .env
